# Generated by Django 3.2.8 on 2021-10-30 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropplantation',
            name='harvested_date',
            field=models.DateField(blank=True),
        ),
    ]
