# Generated by Django 3.2.8 on 2021-10-30 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0004_auto_20211030_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropplantation',
            name='soil_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farmer.soilhealth'),
        ),
    ]
