# Generated by Django 3.2.8 on 2021-10-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crops',
            name='photo',
            field=models.ImageField(upload_to='static/images/crops/'),
        ),
    ]
