# Generated by Django 3.2.8 on 2021-10-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soil_health', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soilhealth',
            old_name='soil_ph',
            new_name='ph',
        ),
        migrations.RenameField(
            model_name='soilhealth',
            old_name='potassium',
            new_name='potas',
        ),
        migrations.RemoveField(
            model_name='soilhealth',
            name='soil_type',
        ),
        migrations.AddField(
            model_name='soilhealth',
            name='rainfall',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soilhealth',
            name='temp',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
